"""

Revision ID: 2671f8bd80dc
Revises: 8246f3b81a66
Create Date: 2023-08-28 13:13:00.266003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2671f8bd80dc"
down_revision = "8246f3b81a66"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "students",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("profile_picture", sa.String(), nullable=False),
        sa.Column("sprite", sa.String(), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("students_pkey")),
    )
    op.create_table(
        "sensei_messages",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("sensei_messages_student_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("sensei_messages_pkey")),
    )
    op.create_index(
        op.f("sensei_messages_student_id_idx"),
        "sensei_messages",
        ["student_id"],
        unique=False,
    )
    op.create_table(
        "student_messages",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("student_messages_student_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("student_messages_pkey")),
    )
    op.create_index(
        op.f("student_messages_student_id_idx"),
        "student_messages",
        ["student_id"],
        unique=False,
    )
    op.create_table(
        "student_phrases",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("phrase", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("student_phrases_student_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("student_phrases_pkey")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("student_phrases")
    op.drop_index(
        op.f("student_messages_student_id_idx"), table_name="student_messages"
    )
    op.drop_table("student_messages")
    op.drop_index(op.f("sensei_messages_student_id_idx"), table_name="sensei_messages")
    op.drop_table("sensei_messages")
    op.drop_table("students")
    # ### end Alembic commands ###
